// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVijnXqzAW4BIbhwwL9Mw533ibK5HbPR0',
    appId: '1:1057410379070:web:4a64313390cf5e8b92d06f',
    messagingSenderId: '1057410379070',
    projectId: 'chat-app-917ba',
    authDomain: 'chat-app-917ba.firebaseapp.com',
    storageBucket: 'chat-app-917ba.appspot.com',
    measurementId: 'G-ZLLJQBK0GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrELvsxyd1EvMEVCXUkzq8ge9nWlaYQAQ',
    appId: '1:1057410379070:android:7db50d553a4eb80792d06f',
    messagingSenderId: '1057410379070',
    projectId: 'chat-app-917ba',
    storageBucket: 'chat-app-917ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ALUOePEDC-x7Nc0td_CJ0mBGpfRY3xs',
    appId: '1:1057410379070:ios:e37ef866212589be92d06f',
    messagingSenderId: '1057410379070',
    projectId: 'chat-app-917ba',
    storageBucket: 'chat-app-917ba.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ALUOePEDC-x7Nc0td_CJ0mBGpfRY3xs',
    appId: '1:1057410379070:ios:16ac24ac06b3bc8992d06f',
    messagingSenderId: '1057410379070',
    projectId: 'chat-app-917ba',
    storageBucket: 'chat-app-917ba.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
